<?php
error_reporting(0);
echo "Adınız:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["ad"];
echo "<br>";
echo "Soyadınız:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["soyad"];
echo "<br>";
echo "Mailiniz:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["mail"];
echo "<br>";
echo "Cinsiyetiniz:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["cinsiyet"];
echo "<br>";
echo "En sevdiğiniz spor dalı:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["spor1"];
echo $_POST["spor2"];
echo $_POST["spor3"];
echo $_POST["spor4"];
echo $_POST["spor5"];
echo $_POST["spor6"];
echo $_POST["spor7"];
echo $_POST["spor8"];
echo "<br>";
echo "Hobileriniz:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["hobi1"];
echo $_POST["hobi2"];
echo $_POST["hobi3"];
echo $_POST["hobi4"];
echo $_POST["hobi5"];
echo $_POST["hobi6"];
echo $_POST["hobi7"];
echo "<br>";
echo "Bize kendinden bahset:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["mesaj"];
echo "<br>";
echo "Tuttuğun Takım:&nbsp&nbsp";
echo $_POST["Takım"];
echo "<br>";
echo "Okuduğun Üniversite:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp";
echo $_POST["Universite"];
echo "<br>";
echo "<br>";
echo "<br>";
?>